function Exo1()
{
    $.ajax
    (
        {
            type:"get",
            url:"index.php/controllerDevoir/afficherCreateConf",
            success:function(data)
            {
                $('#divCreate').empty();
                $('#divCreate').append(data);
            },
            error:function()
            {
                alert("Erreur.");
            }
        }
    );
}
